# Generated by Django 3.2.6 on 2021-09-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['postcode', 'name', 'address'],
            },
        ),
        migrations.CreateModel(
            name='LocationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationSlots', to='bupaBooking.location')),
            ],
            options={
                'ordering': ['location', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('code', models.IntegerField(choices=[(501, '501 Medical Examination'), (502, '502 Chest X-Ray'), (704, '704 Serum Creatinine'), (707, '707 HIV test'), (708, '708 Hepatitis B test')], primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('locationSlots', models.ManyToManyField(related_name='users', to='bupaBooking.LocationSlot')),
                ('medicalItems', models.ManyToManyField(related_name='users', to='bupaBooking.MedicalItem')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
        ),
        migrations.AddField(
            model_name='locationslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationSlots', to='bupaBooking.slot'),
        ),
        migrations.AddField(
            model_name='location',
            name='slots',
            field=models.ManyToManyField(related_name='locations', through='bupaBooking.LocationSlot', to='bupaBooking.Slot'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address', 'postcode')},
        ),
    ]
