# Generated by Django 3.2.6 on 2021-08-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('times', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bupaBooking.availabletime', verbose_name='Times')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('dates', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bupaBooking.availabledate', verbose_name='Dates')),
            ],
            options={
                'ordering': ['name', 'address', 'postcode'],
                'unique_together': {('name', 'address', 'postcode')},
            },
        ),
    ]
