# Generated by Django 3.2.6 on 2021-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=4),
        ),
    ]
