# Generated by Django 3.2.6 on 2021-08-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0002_alter_location_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='times',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupaBooking.availabletime', verbose_name='Times'),
        ),
        migrations.AlterField(
            model_name='location',
            name='dates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupaBooking.availabledate', verbose_name='Dates'),
        ),
    ]
