# Generated by Django 3.2.6 on 2021-08-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0003_auto_20210825_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='dates',
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
        migrations.AddField(
            model_name='location',
            name='slots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupaBooking.datetimeslot', verbose_name='Dates'),
        ),
    ]
