# Generated by Django 3.2.6 on 2021-08-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0004_auto_20210825_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slots',
        ),
        migrations.AddField(
            model_name='location',
            name='slots',
            field=models.ManyToManyField(to='bupaBooking.DateTimeSlot'),
        ),
    ]
