# Generated by Django 3.2.6 on 2021-08-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('code', models.IntegerField(choices=[(501, 'Medical Examination'), (502, 'Chest X-Ray'), (704, 'Serum Creatinine'), (707, 'HIV test'), (708, 'Hepatitis B test')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='slots',
        ),
        migrations.CreateModel(
            name='LocationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationSlots', to='bupaBooking.location')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationSlots', to='bupaBooking.slot')),
            ],
            options={
                'ordering': ['location', 'slot'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='locationSlots',
            field=models.ManyToManyField(related_name='users', to='bupaBooking.LocationSlot'),
        ),
        migrations.AddField(
            model_name='user',
            name='medicalItems',
            field=models.ManyToManyField(related_name='users', to='bupaBooking.MedicalItem'),
        ),
    ]
