# Generated by Django 3.2.6 on 2021-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupaBooking', '0009_auto_20210829_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalitem',
            name='code',
            field=models.IntegerField(choices=[(501, '501 Medical Examination'), (502, '502 Chest X-Ray'), (704, '704 Serum Creatinine'), (707, '707 HIV test'), (708, '708 Hepatitis B test')], primary_key=True, serialize=False),
        ),
    ]
